### ISSUE TITLE
 Hook Class访问内部成员的Method

### ISSUE THREAD

**Issue by Yan-Zero** [bigbaldy1128/DotNetDetour#12]
举个例子
`    public class Student
    {
        private int ID;
        private string Name;

        public Student(string name ,int id = -1)
        {
            Name = name;
            ID = id;
        }

        public string printName()
        {
            return Name;
        }
    }

    public static class Main
    {
        public static void Test()
        {
            Student student = new Student("A",97);

            Console.WriteLine(student.printName());
        }
    }`

我要Hook printName，让它多回一个ID
怎么办？

**Comment by xiangyuecn** [comment]
直接手打了，没有测试，基本原理就是这样，因为你要用到当前对象里面的值，所以要传递数据，会复杂些
``` C#
class Main{
	public static void Test(){
		MethodHook.Install();
		
		Student student = new Student("A",97);
		
		CallContext.LogicalSetData("id", student..反射获取私有..ID);//传递变量
		Console.WriteLine(student.printName());
	}
}


//Hook实现类
class MyHook: IMethodHook{
	[HookMethod("??????.Student")]
	public static string printName(){
		//借助上下文环境中的数据存储来传递当前对象的某些值
		return printName_Original()+" "+CallContext.LogicalGetData("id");
	}
	
	[OriginalMethod]
	public static string printName_Original() {
		return null;
	}
}
```
