### ISSUE TITLE
跨程序执行怎么不成功？

### ISSUE THREAD

**Issue by e-jlion** [bigbaldy1128/DotNetDetour#17]
比如程序A里面执行程序A里面的方法FunA ，我们写一个程序B 让程序A执行他们自己的FunA 方法的时候，直接拦截执行到我们的程序B 里面的方法FunB

**Comment by e-jlion** [comment]
一直执行不成功

**Comment by xiaoyao66** [comment]
如何跨程序执行？使用进程外COM？

**Comment by xiaoyao66** [comment]
你是说跨模块还是跨进程？是你的模块B要 Hook 原始模块A里的函数FunA？

**Comment by e-jlion** [comment]
> 你是说跨模块还是跨进程？是你的模块B要 Hook 原始模块A里的函数FunA？

跨进程 A,B都是运行中的两个进程，想通过hook方式修改掉原始进程的方法内容

**Comment by e-jlion** [comment]
> > 你是说跨模块还是跨进程？是你的模块B要 Hook 原始模块A里的函数FunA？
> 
> 跨进程 A,B都是运行中的两个进程，想通过hook方式修改掉原始进程的方法内容

例子中只是跨了模块，还是在同一个进程中，而大多时候可能需要跨进程修改

**Comment by e-jlion** [comment]
跨模块感觉意义不大，只是在同一个进程中修改原始模块dll中的方法而已

**Comment by xiaoyao66** [comment]
跨进程是另外一种技术，和Hook没啥关系了就。Hook都是对本进程的模块进行处理的。
你需要的跨进程方法叫做Hijack，是另外一种技术分类。

**Comment by a312586670** [comment]
> Hijack

感谢，我还以为这个可以跨进程呢

**Comment by e-jlion** [comment]
> 跨进程是另外一种技术，和Hook没啥关系了就。Hook都是对本进程的模块进行处理的。
> 你需要的跨进程方法叫做Hijack，是另外一种技术分类。

感谢，我还以为这个可以跨进程呢

**Comment by e-jlion** [comment]
> 跨进程是另外一种技术，和Hook没啥关系了就。Hook都是对本进程的模块进行处理的。
> 你需要的跨进程方法叫做Hijack，是另外一种技术分类。

有方案了，使用这个弄一个dll模块，再通过win32 api 把这个dll 动态注入到某个进程里面去，方法就可以实现拦截了

**Comment by doudouhala** [comment]
> > 跨进程是另外一种技术，和Hook没啥关系了就。Hook都是对本进程的模块进行处理的。
> > 你需要的跨进程方法叫做Hijack，是另外一种技术分类。
> 
> 有方案了，使用这个弄一个dll模块，再通过win32 api 把这个dll 动态注入到某个进程里面去，方法就可以实现拦截了

注入进取之后怎么调用MethodHook.Install 呢？C#写的dll没有dllmain这一说法，怎么让他自动调用

**Comment by e-jlion** [comment]
> > > 跨进程是另外一种技术，和Hook没啥关系了就。Hook都是对本进程的模块进行处理的。
> > > 你需要的跨进程方法叫做Hijack，是另外一种技术分类。
> > 
> > 
> > 有方案了，使用这个弄一个dll模块，再通过win32 api 把这个dll 动态注入到某个进程里面去，方法就可以实现拦截了
> 
> 注入进取之后怎么调用MethodHook.Install 呢？C#写的dll没有dllmain这一说法，怎么让他自动调用

你可以看我这个 Demo  源代码：https://github.com/e-jlion/processClientDemo
