### ISSUE TITLE
hook同名属性会有问题

### ISSUE THREAD

**Issue by xLabel** [bigbaldy1128/DotNetDetour#6]
@kissstudio @bigbaldy1128 

A、B class ，均有名字一样的属性（返回类型不一样），导致运行时影子(原始)属性返回值均为null

伪代码如图示：
class A{
 public List<int> HH{get;}
}

class B{
 public List<string> HH{get;}
}

**Comment by linsmod** [comment]
贴代码

**Comment by xLabel** [comment]
@kissstudio  
项目代码比较复杂，我在单元测试里简单做个例子

mock2个class
```
   //模拟与原Computer类均有一个同名的属性get_Os
   public class NewComputer
    {
        public int[] Os
        {
            get
            {
                return new[] { 9527 };
            }
        }
    }

   //hook
    public class NewDetour : IMethodHook
    {
        public int[] _impl_Os
        {
            [RelocatedMethod(typeof(NewComputer), "get_Os")]
            get
            {
                var ss = this.Os;
                return new[] { 11111 };
            }
        }

        public int[] Os
        {

            [ShadowMethod(typeof(NewComputer), "get_Os")]
            get
            {
                return null;
            }
        }
    }
```
main入口
```
 class Program
    {
        static void Main(string[] args)
        {
            ClrMethodHook.Install();

            var old = new Computer().Os;
            var new1 = new NewComputer().Os;

            Console.ReadKey();
        }
    }
```

**Comment by linsmod** [comment]
引用的库执行install了吗，还有，直接写方法而不是属性呢

**Comment by xLabel** [comment]
> 引用的库执行install了吗，还有，直接写方法而不是属性呢

你好，有执行install操作的。上面贴的代码就是在原来的单元测试Samples.cs里直接增加就可以测了

直接写方法是什么意思？现在是hook属性，不是方法哦，还是我打开方式不对- -
```
  class Program
    {
        static void Main(string[] args)
        {
            ClrMethodHook.Install();

            var old = new Computer().Os;
            var new1 = new NewComputer().Os;

            Console.ReadKey();
        }
    }
```

**Comment by linsmod** [comment]
参考demo

**Comment by xLabel** [comment]
> 参考demo

确信这是BUG导致的，不是用法问题。

业务上是hook，wcf的调度器分别是

客户端ClientRuntime的MessageInspectors属性
https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Dispatcher/ClientRuntime.cs,2b625eba9081c5a2,references

服务端DispatchRuntime的MessageInspectors属性
https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Dispatcher/DispatchRuntime.cs,c54945efc884904c

当单纯只hook客户端或者服务端其中一个是没任何问题的，但两个同时hook就出现问题了，能不能修复就另外一回事 : )

至于为什么推断跟属性名有关，是基于同时hook客户端以及服务端时，故意把ShaodowMethod特性中的methodname写成不同的，就顺利hook成功其中一端了。

**Comment by xiangyuecn** [comment]
老代码上已复现，老代码是有几个蛮大的问题。

我这两天在优化代码，在我新代码上没有复现这个问题，已经给仓库提交PR了 @kissstudio @bigbaldy1128 可以合并一下吗？README也改好看了好多 :grin:

 @xLabel 没有合并代码前可以去我那分支试试新代码，好像自然解决了你这个问题:smiley:

**Comment by xiangyuecn** [comment]
#7

**Comment by xiangyuecn** [comment]
https://github.com/bigbaldy1128/DotNetDetour/blob/b5f9f5815465ddb2e55c599def749f68153b18d0/DotNetDetour/Monitor.cs#L62-L82

导致此问题的原因在于所有ShadowMethod都是在整个已加载的程序集中查找（clrMethods中），名称和参数签名相同的只会返回第一个ShadowMethod。

clrMethod赋值那行验证一下类型是否和item的相同就解决了此问题。
``` C#
&& x.ReflectedType==item.ReflectedType
```

我那边写的代码和这个库最原始的代码差不多，都是直接在同一个类下面查找Hook和Shadow方法，所以天然免疫了此问题：
https://github.com/bigbaldy1128/DotNetDetour/blob/855cf82b3955e36fa907351da2f74c870c82c339/DotNetDetour/Monitor.cs#L61-L76

**Comment by xLabel** [comment]
@xiangyuecn thanks，针对props测试通过。

@bigbaldy1128 这个issue可以Close了
